### ISSUE TITLE
Adding Property to Package using the AADL Property Value View triggers an exception

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#282]
Adding Property to Package using the AADL Property Value View triggers an exception.

Steps to reproduce:
-Open test model.
-Open the AADL Property Values view
-Click the end of the first line
-Verify that the package itself has been selected by confirming that the Source_Text property appears in the view.
-Click the add property association button.
-Select a property to add.
```
package pgk_properties_test


public

properties
	Programming_Properties::Source_Text => ("Test");
end pgk_properties_test;
```

Stack trace:
```
!ENTRY org.eclipse.jface 4 2 2013-08-23 12:39:46.891
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.osate.aadl2.modelsupport.util.AadlUtil.isImportedPropertySet(AadlUtil.java:2150)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage.attachToModelAndRunLinker(PropertyValueWizardPage.java:292)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage.access$2(PropertyValueWizardPage.java:284)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage$5.process(PropertyValueWizardPage.java:274)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage$5.process(PropertyValueWizardPage.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:36)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:53)
	at org.eclipse.xtext.ui.editor.model.edit.ReconcilingUnitOfWork.exec(ReconcilingUnitOfWork.java:1)
	at org.eclipse.xtext.util.concurrent.AbstractReadWriteAcces.modify(AbstractReadWriteAcces.java:81)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:201)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:98)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.modify(XtextDocument.java:91)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage.attemptToParseValueText(PropertyValueWizardPage.java:271)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage.updatePageComplete(PropertyValueWizardPage.java:247)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyValueWizardPage.setDefinitionImpl(PropertyValueWizardPage.java:147)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.AbstractPropertyValueWizardPage.setDefinition(AbstractPropertyValueWizardPage.java:15)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyAssociationWizard$2.propertyDefinitionSelectionChanged(PropertyAssociationWizard.java:157)
	at org.osate.xtext.aadl2.ui.propertyview.associationwizard.PropertyDefinitionWizardPage$5.selectionChanged(PropertyDefinitionWizardPage.java:199)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:164)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:162)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2188)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1211)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1241)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:239)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:233)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
	at org.eclipse.jface.window.Window.open(Window.java:802)
	at org.osate.xtext.aadl2.ui.propertyview.AadlPropertyView$2.run(AadlPropertyView.java:201)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:452)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
```

**Comment by lwrage** [comment]
Fixed by removing the property wizard in 802fcc833190fdf7d24f03269bed8dbe12abc8fb
