### ISSUE TITLE
Marker id .. not found

### ISSUE THREAD

**Issue by Etienne13** [osate/osate2-core#629]
I just downloaded the laxest sources of osate2-code (develop branch) and osate2-ba (develop branch as well).

After importing BA examples, I obtain lots of exception traces of type:

!ENTRY org.osate.aadl2.modelsupport 4 0 2015-09-30 18:58:11.322
!MESSAGE *** Internal error: Marker id 37 not found.
!STACK 1
org.eclipse.core.internal.resources.ResourceException: Marker id 37 not found.
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:57)
	at org.eclipse.core.internal.resources.Marker.setAttribute(Marker.java:237)
	at org.eclipse.core.internal.resources.Marker.setAttribute(Marker.java:223)
	at org.osate.aadl2.modelsupport.errorreporting.MarkerParseErrorReporter.createMarker(MarkerParseErrorReporter.java:90)
	at org.osate.aadl2.modelsupport.errorreporting.MarkerParseErrorReporter.errorImpl(MarkerParseErrorReporter.java:103)
	at org.osate.aadl2.modelsupport.errorreporting.AbstractParseErrorReporter.error(AbstractParseErrorReporter.java:55)
	at org.osate.aadl2.modelsupport.errorreporting.AnalysisToParseErrorReporterAdapter.errorImpl(AnalysisToParseErrorReporterAdapter.java:66)
	at org.osate.aadl2.modelsupport.errorreporting.AbstractAnalysisErrorReporter.error(AbstractAnalysisErrorReporter.java:80)
	at org.osate.aadl2.modelsupport.errorreporting.AnalysisErrorReporterManager.error(AnalysisErrorReporterManager.java:258)
	at org.osate.ba.analyzers.AadlBaLegalityRulesChecker.reportLegalityError(AadlBaLegalityRulesChecker.java:965)
	at org.osate.ba.analyzers.AadlBaLegalityRulesChecker.D_3_L6_Check(AadlBaLegalityRulesChecker.java:428)
	at org.osate.ba.analyzers.AadlBaRulesCheckersDriver$1.caseBehaviorTransition(AadlBaRulesCheckersDriver.java:266)
	at org.osate.ba.analyzers.AadlBaRulesCheckersDriver$1.caseAnnexSubclause(AadlBaRulesCheckersDriver.java:184)
	at org.osate.ba.analyzers.AadlBaRulesCheckersDriver$1.caseAnnexSubclause(AadlBaRulesCheckersDriver.java:1)
	at org.osate.ba.aadlba.util.AadlBaSwitch.doSwitch(AadlBaSwitch.java:238)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.osate.ba.analyzers.AadlBaRulesCheckersDriver.process(AadlBaRulesCheckersDriver.java:96)
	at org.osate.ba.AadlBaResolver.resolveAnnex(AadlBaResolver.java:92)
	at org.osate.annexsupport.AnnexResolverProxy.resolveAnnex(AnnexResolverProxy.java:70)
	at org.osate.xtext.aadl2.parsing.AnnexParserAgent.afterModelLinked(AnnexParserAgent.java:233)
	at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:54)
	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:308)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:108)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:269)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:258)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:171)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:101)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:82)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:261)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:24)
	at org.eclipse.xtext.builder.resourceloader.SerialResourceLoader$1.next(SerialResourceLoader.java:47)
	at org.eclipse.xtext.builder.resourceloader.AbstractResourceLoader$CheckedLoadOperation.next(AbstractResourceLoader.java:77)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:386)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:134)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:115)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:248)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:280)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:117)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

I don't know what the marker id is nor what is the explanation for this. Any idea or suggestion?

Etienne.

**Comment by lwrage** [comment]
This is bug #613
