### ISSUE TITLE
OSATE hangs at startup

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#700]
Sometimes, when starting OSATE, it hangs forever. The log shows the following (see below). 
The only solution is to start OSATE in a new workspace.

!SESSION 2016-04-19 09:36:37.692 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_71
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.osate.branding.osate2
Command-line arguments:  -product org.osate.branding.osate2 -data /home/julien/wip/eclipse-workspace/../runtime-osate -dev file:/home/julien/wip/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/osate/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.core.resources 2 10035 2016-04-19 09:36:44.148
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.emf.ecore 2 0 2016-04-19 09:36:44.991
!MESSAGE Both 'edu.cmu.aaspe.attackimpact' and 'edu.cmu.aaspe.attackimpact' register a package for 'http://www.example.org/attackimpact'

!ENTRY org.eclipse.osgi 2 0 2016-04-19 09:36:50.564
!MESSAGE While loading class "org.eclipse.xtext.ui.shared.internal.ExecutableExtensionFactory", thread "Thread[Worker-0,5,main]" timed out waiting (5001ms) for thread "Thread[main,6,main]" to finish starting bundle "org.eclipse.xtext.ui.shared_2.8.4.v201508050135 [903]". To avoid deadlock, thread "Thread[Worker-0,5,main]" is proceeding but "org.eclipse.xtext.ui.shared.internal.ExecutableExtensionFactory" may not be fully initialized.
!STACK 0
org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; osgi.identity="org.eclipse.xtext.ui.shared"; type="osgi.bundle"; version:Version="2.8.4.v201508050135"; singleton:="true" [id=903] STARTED [STARTED]
    at org.eclipse.osgi.container.Module.lockStateChange(Module.java:329)
    at org.eclipse.osgi.container.Module.start(Module.java:389)
    at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
    at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
    at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
    at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:402)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:573)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:901)
    at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:854)
    at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:546)
    at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:575)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:243)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.equinox.ds 2 0 2016-04-19 09:36:56.772
!MESSAGE Getting a lock required more than 10000 ms. There might be a synchronization problem in this callstack or just the build/dispose process of some components took too long! 
!STACK 0
java.lang.Exception: Debug stacktrace
    at org.eclipse.equinox.internal.ds.InstanceProcess.getLock(InstanceProcess.java:120)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:560)
    at org.eclipse.equinox.internal.ds.ServiceReg.getService(ServiceReg.java:53)
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210)
    at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111)
    at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:496)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:619)
    at org.eclipse.pde.internal.core.PDECore.acquireService(PDECore.java:369)
    at org.eclipse.pde.internal.core.P2Utils.getBundlesFromFile(P2Utils.java:181)
    at org.eclipse.pde.internal.core.P2Utils.readBundles(P2Utils.java:111)
    at org.eclipse.pde.internal.core.target.ProfileBundleContainer.resolveBundles(ProfileBundleContainer.java:115)
    at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:82)
    at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:294)
    at org.eclipse.pde.internal.core.TargetPlatformHelper.getWorkspaceTargetResolved(TargetPlatformHelper.java:485)
    at org.eclipse.pde.internal.core.PluginModelManager.getExternalBundles(PluginModelManager.java:625)
    at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:545)
    at org.eclipse.pde.internal.core.PluginModelManager.targetReloaded(PluginModelManager.java:473)
    at org.eclipse.pde.internal.core.RequiredPluginsInitializer$1.run(RequiredPluginsInitializer.java:35)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by juli1** [comment]
for information, removing .metadata/.plugins/org.eclipse.pde.core in the workspace solved the issue.

**Comment by lwrage** [comment]
I have seen that, too. It seems to be xtext related, so there's probably nothing we can do about it. Also it happens during development only, not when starting the product.

**Comment by lwrage** [comment]
The issue seems to have gone away after the update to xtext 2.11.
