### ISSUE TITLE
property assignment issue

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#733]
When I tried to declare a new property, I got a dialog box error with the following stack strace.

org.eclipse.emf.common.util.WrappedException: java.lang.NullPointerException
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:233)
    at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:136)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
    at org.osate.xtext.aadl2.ui.propertyview.CachePropertyLookupJob.lambda$0(CachePropertyLookupJob.java:114)
    at org.osate.xtext.aadl2.ui.propertyview.AadlPropertyView.lambda$15(AadlPropertyView.java:2164)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at org.osate.xtext.aadl2.ui.propertyview.AadlPropertyView.safeRead(AadlPropertyView.java:2166)
    at org.osate.xtext.aadl2.ui.propertyview.CachePropertyLookupJob.run(CachePropertyLookupJob.java:234)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
    at org.eclipse.xtext.linking.impl.LinkingHelper.getRuleNameFrom(LinkingHelper.java:41)
    at org.eclipse.xtext.linking.impl.LinkingHelper.getCrossRefNodeAsString(LinkingHelper.java:56)
    at org.osate.xtext.aadl2.properties.linking.PropertiesLinkingService.getCrossRefNodeAsString(PropertiesLinkingService.java:233)
    at org.osate.xtext.aadl2.linking.Aadl2LinkingService.getLinkedObjects(Aadl2LinkingService.java:149)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:225)
    ... 11 more

**Comment by juli1** [comment]
![errordialog](https://cloud.githubusercontent.com/assets/993972/17567480/85fda83e-5f0d-11e6-9b19-c0b2efd26f68.PNG)

**Comment by juli1** [comment]
Another trace:

!ENTRY org.eclipse.core.jobs 4 2 2016-08-10 15:19:19.629
!MESSAGE An internal error occurred during: "Updating Property View".
!STACK 0
org.eclipse.emf.common.util.WrappedException: java.lang.NullPointerException
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:233)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:136)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.osate.xtext.aadl2.ui.propertyview.CachePropertyLookupJob.lambda$0(CachePropertyLookupJob.java:114)
	at org.osate.xtext.aadl2.ui.propertyview.AadlPropertyView.lambda$15(AadlPropertyView.java:2164)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.osate.xtext.aadl2.ui.propertyview.AadlPropertyView.safeRead(AadlPropertyView.java:2166)
	at org.osate.xtext.aadl2.ui.propertyview.CachePropertyLookupJob.run(CachePropertyLookupJob.java:234)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getNode(LazyURIEncoder.java:255)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.decode(LazyURIEncoder.java:135)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:224)
	... 11 more

**Comment by lwrage** [comment]
Can you please explain in detail when this happened? Is it reproducible?
