### ISSUE TITLE
Instantiate action active on interface components

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2-core#943]
The "Instantiate" action is active in the Outline view context menu for elements that aren't system implementations.  Invoking the action on these items results in an exception:

java.lang.NullPointerException
	at org.osate.ui.handlers.InstantiateHandler$1.lambda$0(InstantiateHandler.java:168)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by AaronGreenhouse** [comment]
A few more notes:

- Instances of non-system implementations are supposed to be okay.
- The problem here is that OSATE allows interfaces to be instantiated.
- Doing so causes an exception.



```
package Mypackage

public
	with SEI;
	
	system S 
	end S;
	
	bus B
	end B;
	
	device D
	end D;
	
	device DD
	end DD;
	
	device DDD
	end DDD;
		
	device implementation D.i
	end D.i;

	system implementation S.i
		subcomponents
			c1: device D;
			c2: device DDD;
			b1: bus B;
			
	properties
			SEI::WeightLimit => 5.0kg;
	end S.i;

end Mypackage;
```

**Comment by AaronGreenhouse** [comment]
So OSATE shows the Instantiate action as enabled in the Outline view context menu for the package, for hte interfaces S, B, D, DD, DDD, and the implementations D.i and S.i. Also for the subcompents of S.i.

Should only show the action for the implementations D.i and S.i.

Right now invoking the action on the subcomponents doesn't throw an exception.  Seems to silently do nothing.  Invoking the action on the implementations creates an instance model of the implementation.  Invoking on the interface declarations or the package declaration causes an exception.

**Comment by AaronGreenhouse** [comment]
Talked to Joe.  This is a known issue resulting from the recent redo of all the old actions into commands.  This affects more things than just the Instantiate action.  Discussed with him how to use the activeWhen and visibleWhen elements in the plugin.xml to handle this problem.

**Comment by AaronGreenhouse** [comment]
Okay, so added an enabledWhen element to the handler for the instantiate command.  It works for the context menu in the AADL Navigator, but not the outline view.  This is becuase the navigator model has Eobjects in it, but the outline view has EObjectNode objects in it.  So we need to create a PropertyTester extension point to test the EClass of the EObjectNode, specifically that it has a certain supertype.  This can be made more generic by using attribute strings and Aadl2package.getEClassifier() to get the EClass to test against.  The selected EObjectNode can be adapted to an EClass.

Look at 

https://github.com/joeseibel/budgeting/blob/master/budgeting.ui.populate/plugin.xml

for an example of a property tester.

**Comment by AaronGreenhouse** [comment]
Created org.osate.ui.EObjectNodeAadlSuperTypePropertyTester and registered it as a PropertyTester for EObjectNode instances, with the property "superType".  Uses the 'value' attribute to name the ancestor type to test for.  This should be useful for other UI changes in the future.

Updated the command definition so that it works for both EObject and EObjectNode.  

Updated the menu declaration so that command doesn't appear if it is not enabled.
