### ISSUE TITLE
Workflow edit/view/execute actions throw exception when no model is set

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2-core#950]

**Comment by AaronGreenhouse** [comment]
The workflows do not handle the case of the instance model not being set withing the workflow.  When this happens the actions on the edit/view buttons on the flow components throw exceptions.  The action for executing the analysis throws an exception.

For example, the "Run Unbound Memory Analysis" actoin on the Memory workflow has the following error

!ENTRY org.eclipse.ui 4 0 2017-11-28 12:38:30.731
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.core.internal.resources.ResourceException: Resource '/Testing123/instances/system1.aaxl2' does not exist.
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
	at org.osate.workbench.ui.workflow.memory.MemoryMediator$4.run(MemoryMediator.java:172)
	at org.eclipse.gmf.internal.bridge.ui.dashboard.HyperlinkFigure$1.mousePressed(HyperlinkFigure.java:63)
	at org.eclipse.draw2d.Figure.handleMousePressed(Figure.java:938)
	at org.eclipse.draw2d.SWTEventDispatcher.dispatchMousePressed(SWTEventDispatcher.java:242)
	at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseDown(LightweightSystem.java:523)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.eclipse.core.internal.resources.ResourceException: Resource '/Testing123/instances/system1.aaxl2' does not exist.
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:335)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:209)
	at org.eclipse.core.internal.resources.File.getContents(File.java:275)
	at org.eclipse.core.internal.resources.File.getContents(File.java:268)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl$WorkbenchHelper.createPlatformResourceInputStream(PlatformResourceURIHandlerImpl.java:207)
	at org.eclipse.emf.ecore.resource.impl.PlatformResourceURIHandlerImpl.createInputStream(PlatformResourceURIHandlerImpl.java:525)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:298)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1269)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 35 more


This is probably simple to fix by having the actions check if the instance is set yet.

**Comment by AaronGreenhouse** [comment]
Joe pointed out that he checks for this case in the binpacking workflow.  This does seem to be the case.  Also, the error model workflow seems to be okay.

Need to look at the binpacking workflow and see what it is doing that the other ones are not.

**Comment by AaronGreenhouse** [comment]
This is more compicated than originally presented.  If you start up with no projects in the workdspace, and open the workflows, they behave as is desired: the actions on the workflow square are disabled until an instance model is selected.  But for some workflows the actions for actually executing the analysis are (wrongly) enabled.

Things go bad when you then delete the instance model that is associated with the workflow.

**Comment by AaronGreenhouse** [comment]
In fact, binpacking is the worst offender, if you delete the intance model, the flow lines disappear!

If you reinstantiate the missing instance model, then Bandwidth is happy to continue using it as if nothing happened.  Binpacking gets its flow lines back, but returns to having no model specified.

**Comment by AaronGreenhouse** [comment]
The "Synchronize with workbench" interacts with this problem.  I need a better understanding of what it is meant to do, and what the desired behavior for workflows really is.  

In any case, we definitely need to track whether the selected instance model is deleted and react appropriately.  Probably there is some of kind of ResourceEvent we can register for here.

**Comment by AaronGreenhouse** [comment]
Also check what happens when you close/open a project

**Comment by AaronGreenhouse** [comment]
Upated the binpacking workflow.  Now I need to generalize the other workflows.

**Comment by AaronGreenhouse** [comment]
Created abstract state, mediator, figure, and workflow classes.  Have updated Binpacking and Bandwidth workflwos to used them.  Now both flows are fixed for the bug of deleting the instance model file.  Need to update the rest of the workflows.

**Comment by AaronGreenhouse** [comment]
Udated everything but ErorrModel workflow.  Need to wait for peter to fix stuff first?

Interestingly, the error model workflow already has a resource listener.  May need to generalize my approach that is n the abstract Workflow classes I made.

**Comment by AaronGreenhouse** [comment]
Updated a few things in WorkflowMediator based on how the resource listener in ErrorModelMediator is written.

**Comment by AaronGreenhouse** [comment]
ErrorModel workflow is updated and integrated into the abstract class pattern I created.  The resource listener is created in WorkflowPart, and ErrorModel is able to link it's extensions into it.

Everything seems to be working.
