### ISSUE TITLE
Instantiating subcomponents with unbound prototypes caues exception

### ISSUE THREAD

**Issue by AaronGreenhouse** [osate/osate2-core#986]
Instantiating this model causes an exception.  Granted, this model probably fails some kind of consistency constraint as the prototype X is unbound, but we should not just bomb out.

	package package1
	public
		system s
		end s;
	
		system implementation s.i
		prototypes
			X: bus;
		subcomponents
			b: bus X;
		end s.i;
	end package1;

We get the exception

java.lang.NullPointerException
	at org.osate.aadl2.instantiation.InstantiateModel.getAllUsedPropertyDefinitions(InstantiateModel.java:1932)
	at org.osate.aadl2.instantiation.InstantiateModel.getUsedPropertyDefinitions(InstantiateModel.java:492)
	at org.osate.aadl2.instantiation.InstantiateModel.fillSystemInstance(InstantiateModel.java:465)
	at org.osate.aadl2.instantiation.InstantiateModel.createSystemInstanceInt(InstantiateModel.java:397)
	at org.osate.aadl2.instantiation.InstantiateModel$1.doExecute(InstantiateModel.java:339)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:208)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.osate.aadl2.instantiation.InstantiateModel.createSystemInstance(InstantiateModel.java:351)

**Comment by AaronGreenhouse** [comment]
Strangely there is no consistency rule for operational systems that requires all prototypes to be bound.

In any case, this definitely means instantiation should not be crashing on this model.

**Comment by lwrage** [comment]
You could report the missing consistency rule at the standard issue tracker. It's  saeaadl/aadlv2.2 on github.

I think the instantiation should work as follows:

For feature groups and subcomponents that refer to a prototype
* if there is a prototype binding, use that
* else if the prototype declaration comes with a classifier, use that
* else create an instance object without classifier reference.

For feature prototypes without actual, create an abstract feature instance.

**Comment by AaronGreenhouse** [comment]
This error occurs during some kind of property look up.  But the problem is caused by the fact that the unbound prototype `X` doesn't resolve to anything.  So we end up with an InstantiatedClassifier object that has a `null` classifier attribute.  When later clients try to use the IC they run into trouble.

I don't see much info in the standard about the semantics of this situation.  The section on prototypes is only a few pages, and never really discusses the semantics of instantiating them.  As mentioned above, there is no requirement for systems to have all the prototypes be fully specified.  

Clearly there is a higher level problem with the model if you are trying to instantiate it in this situation.  But it shouldn't crash.  I think the solution right now is 
1. Emit a warning on the model that the classifier of the feature/component/whatever is unknown because the prototype is unbound
2. internally treat the situation the same as if the classifier were simply absent so that the rest of the operations can complete without error.  This means instead of returning an InstantiatedClassifier object with null components, just returning `null` as the classifier.

**Comment by lwrage** [comment]
Agreed, except that if the prototype declaration has a classifier, then that classifier should be used even if the prototype is not bound. Assume that in the model below we directly instantiate A.i. Then, even though pr is unbound, the component instance created from subcomponent s should have B as its classifier.

```
...

bus B
end B;

...

abstract implementation A.i
  prototype
    pr: bus B; -- B is a constraint on the prototype actual, the actual must extend or 
               -- implement B depending on property Prototype_Substitution_Rule
  subcomponent
    s: bus pr;
end A.i;

...
```

**Comment by AaronGreenhouse** [comment]
Yes.  I forgot about that case.

**Comment by AaronGreenhouse** [comment]
Fixed this.
